import math,string,itertools,fractions,heapq,collections,re,array,bisect,random

class CatAndRat:
    def getTime(self, R, T, Vrat, Vcat):
        harf_cir = float(R * math.pi)
        t_dis = float(Vrat * T)
        if Vrat >= Vcat:
        	return -1.0
        elif harf_cir > t_dis:
        	return t_dis / (Vcat - Vrat)
        else:
        	return harf_cir / (Vcat - Vrat)

# BEGIN KAWIGIEDIT TESTING
# Generated by KawigiEdit-pf 2.3.0
import sys
import time
def KawigiEdit_RunTest(testNum, p0, p1, p2, p3, hasAnswer, p4):
	sys.stdout.write(str("Test ") + str(testNum) + str(": [") + str(p0) + str(",") + str(p1) + str(",") + str(p2) + str(",") + str(p3))
	print(str("]"))
	obj = CatAndRat()
	startTime = time.clock()
	answer = obj.getTime(p0, p1, p2, p3)
	endTime = time.clock()
	res = True
	print(str("Time: ") + str((endTime - startTime)) + str(" seconds"))
	if (hasAnswer):
		res = answer == answer and abs(p4 - answer) <= 1e-9 * max(1.0, abs(p4))
	
	if (not res):
		print(str("DOESN'T MATCH!!!!"))
		if (hasAnswer):
			print(str("Desired answer:"))
			print(str("\t") + str(p4))
		
		print(str("Your answer:"))
		print(str("\t") + str(answer))
	elif ((endTime - startTime) >= 2):
		print(str("FAIL the timeout"))
		res = False
	elif (hasAnswer):
		print(str("Match :-)"))
	else:
		print(str("OK, but is it right?"))
	
	print(str(""))
	return res

all_right = True
tests_disabled = False


# ----- test 0 -----
disabled = False
p0 = 10
p1 = 1
p2 = 1
p3 = 1
p4 = -1.0
all_right = (disabled or KawigiEdit_RunTest(0, p0, p1, p2, p3, True, p4) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 1 -----
disabled = False
p0 = 10
p1 = 1
p2 = 1
p3 = 2
p4 = 1.0
all_right = (disabled or KawigiEdit_RunTest(1, p0, p1, p2, p3, True, p4) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 2 -----
disabled = False
p0 = 10
p1 = 1
p2 = 2
p3 = 1
p4 = -1.0
all_right = (disabled or KawigiEdit_RunTest(2, p0, p1, p2, p3, True, p4) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 3 -----
disabled = False
p0 = 1000
p1 = 1000
p2 = 1
p3 = 1000
p4 = 1.001001001001001
all_right = (disabled or KawigiEdit_RunTest(3, p0, p1, p2, p3, True, p4) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

# ----- test 4 -----
disabled = False
p0 = 1
p1 = 1000
p2 = 1
p3 = 2
p4 = 3.141592653589793
all_right = (disabled or KawigiEdit_RunTest(4, p0, p1, p2, p3, True, p4) ) and all_right
tests_disabled = tests_disabled or disabled
# ------------------

if (all_right):
	if (tests_disabled):
		print(str("You're a stud (but some test cases were disabled)!"))
	else:
		print(str("You're a stud (at least on given cases)!"))
	
else:
	print(str("Some of the test cases had errors."))

# PROBLEM STATEMENT
# We have a circular tube.
# At one point the tube has an entrance.
# 
# At time 0, a rat enters the tube via the entrance.
# The rat can move inside the tube in both directions (clockwise and counterclockwise).
# The rat can change direction in an instant.
# Its maximum speed is Vrat.
# 
# At time T, the cat will enter the tube via the same entrance.
# The cat can also move in both directions and change its direction instantly.
# Its maximum speed is Vcat.
# 
# For the purpose of this problem, you should imagine the tube as a circle with radius R, and the rat and the cat as points on said circle.
# 
# The cat is trying to catch the rat as quickly as possible.
# The rat is trying not to be caught, and if that is impossible, to be caught as late as possible.
# At any time (starting at time 0) the cat and the rat know each other's position.
# Already at time 0 the rat knows the time T.
# Assume that both the cat and the rat behave optimally.
# 
# You are given the integers R, T, Vrat, and Vcat.
# If the cat will catch the rat successfully, return how much time it'll take the cat to catch the rat.
# Otherwise, return -1.0.
# 
# DEFINITION
# Class:CatAndRat
# Method:getTime
# Parameters:integer, integer, integer, integer
# Returns:float
# Method signature:def getTime(self, R, T, Vrat, Vcat):
# 
# 
# NOTES
# -The cat and rat cannot leave the tube.
# -Your return value must have a relative or absolute error less than 1e-9.
# 
# 
# CONSTRAINTS
# -R, T, Vrat, and Vcat will each be between 1 and 1000, inclusive.
# 
# 
# EXAMPLES
# 
# 0)
# 10
# 1
# 1
# 1
# 
# Returns: -1.0
# 
# The rat can survive. During the first unit of time it has to run away from the entrance. Then, once the cat enters the tube, the rat can always run in the same direction and with the same speed as the cat.
# 
# 1)
# 10
# 1
# 1
# 2
# 
# Returns: 1.0
# 
# The cat is now faster than the rat.
# The best strategy for the rat is to enter the tube and to start running in either direction at its maximum speed.
# The cat will then enter the tube, run in the same direction as the rat, and catch it in exactly 1 unit of time.
# 
# 2)
# 10
# 1
# 2
# 1
# 
# Returns: -1.0
# 
# The rat is now faster than the cat. It can survive, for example by using the strategy described in Example 0.
# 
# 3)
# 1000
# 1000
# 1
# 1000
# 
# Returns: 1.001001001001001
# 
# 
# 
# 4)
# 1
# 1000
# 1
# 2
# 
# Returns: 3.141592653589793
# 
# 
# 
# END KAWIGIEDIT TESTING
#Powered by KawigiEdit-pf 2.3.0!
